### ISSUE TITLE
Move the repository to the timvideos organization

### ISSUE THREAD

**Issue by mithro** [timvideos/video-signal-booster-board#10]
This should be the final home.

**Comment by kgugala** [comment]
unfortunately I cannot do that. Github says:
`You don’t have the permission to create public repositories on timvideos`

**Comment by mithro** [comment]
I've invited you to the @timvideos organization now.

**Comment by kgugala** [comment]
done.

**Comment by kgugala** [comment]
the repo has been moved. It seems I don't have rights to close this issue

**Comment by mithro** [comment]
@kgugala Try again now....
